# Strict License Policy
# Very restrictive policy for sensitive projects
# Usage: py-license-auditor --init ci
# Then:  py-license-auditor

[tool.py-license-auditor]
format = "json"
include_unknown = false
fail_on_violations = true
check_violations = true

[tool.py-license-auditor.policy]
name = "Strict License Policy"
description = "Very restrictive - only MIT, Apache-2.0, BSD-3-Clause"

[tool.py-license-auditor.policy.allowed_licenses]
exact = ["MIT", "Apache-2.0", "BSD-3-Clause"]
patterns = []

[tool.py-license-auditor.policy.forbidden_licenses]
exact = ["GPL-2.0", "GPL-3.0", "LGPL-2.1", "LGPL-3.0", "AGPL-3.0", "MPL-2.0"]
patterns = ["GPL-*", "LGPL-*", "AGPL-*"]

[tool.py-license-auditor.policy.review_required]
exact = ["ISC", "BSD-2-Clause"]
patterns = ["BSD-*"]
