name = "Open Source Permissive Policy"
description = "Permissive policy for open source projects"

[allowed_licenses]
exact = ["MIT", "Apache-2.0", "BSD-3-Clause", "ISC", "MPL-2.0"]
patterns = ["BSD-*"]

[forbidden_licenses]
exact = []
patterns = []

[review_required]
exact = ["GPL-3.0", "AGPL-3.0"]
patterns = ["GPL-*", "AGPL-*"]

# No exceptions needed for open source projects
[[exceptions]]
