name = "Corporate License Policy"
description = "Strict policy for proprietary software development"

[allowed_licenses]
exact = ["MIT", "Apache-2.0", "BSD-3-Clause", "ISC"]
patterns = ["BSD-*"]

[forbidden_licenses]
exact = ["GPL-3.0", "AGPL-3.0", "GPL-2.0"]
patterns = ["GPL-*", "AGPL-*", "LGPL-*"]

[review_required]
exact = ["MPL-2.0"]
patterns = []

[[exceptions]]
name = "legacy-package"
version = "1.0.0"
reason = "Legacy dependency, approved by legal team"
