name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      
      - name: Package (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          tar czf ../../../py-license-auditor-${{ matrix.target }}.tar.gz py-license-auditor
      
      - name: Package (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          tar czf ../../../py-license-auditor-${{ matrix.target }}.tar.gz py-license-auditor.exe
      
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: py-license-auditor-${{ matrix.target }}
          path: py-license-auditor-${{ matrix.target }}.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*/py-license-auditor-*.tar.gz
          body: |
            ## Installation
            
            ```bash
            curl -sSL https://raw.githubusercontent.com/yayami3/py-license-auditor/main/install.sh | bash
            ```
            
            Or download the binary for your platform below.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
